@php($registro = $emprestimo ?? null)
<div class="row g-3">
<div class="col-md-6"><label class="form-label">Usuário *</label><select name="id_usuario" class="form-select" required><option value="">Selecione</option>@foreach($usuarios as $usuario)<option value="{{ $usuario->id }}" @selected(old('id_usuario', $registro?->id_usuario ?? session('usuario_id')) == $usuario->id)>{{ $usuario->nome }}</option>@endforeach</select>@error('id_usuario')<div class="text-danger small">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Material *</label><select name="id_material" class="form-select" required><option value="">Selecione</option>@foreach($materiais as $material)<option value="{{ $material->id }}" @selected(old('id_material', $registro?->item?->id_material) == $material->id)>{{ $material->nome }} ({{ $material->quantidade_disponivel }} disponíveis)</option>@endforeach</select>@error('id_material')<div class="text-danger small">{{ $message }}</div>@enderror</div>
<div class="col-md-4"><label class="form-label">Quantidade *</label><input type="number" min="1" name="quantidade" class="form-control" value="{{ old('quantidade', $registro?->item?->quantidade ?? 1) }}" required>@error('quantidade')<div class="text-danger small">{{ $message }}</div>@enderror</div>
<div class="col-md-4"><label class="form-label">Data do empréstimo *</label><input type="date" name="data_emprestimo" class="form-control" value="{{ old('data_emprestimo', $registro?->data_emprestimo ?? now()->toDateString()) }}" required></div>
<div class="col-md-4"><label class="form-label">Devolução prevista</label><input type="date" name="data_devolucao" class="form-control" value="{{ old('data_devolucao', $registro?->data_devolucao) }}"></div>
<div class="col-md-6"><label class="form-label">Status *</label><select name="status" class="form-select" required>@foreach(['ativo'=>'Ativo','devolvido'=>'Devolvido','atrasado'=>'Atrasado'] as $value=>$label)<option value="{{ $value }}" @selected(old('status', $registro?->status ?? 'ativo') === $value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Observação</label><textarea name="observacao" rows="3" class="form-control">{{ old('observacao', $registro?->observacao) }}</textarea></div></div>
