@extends('layout.principal')
@section('title', 'Empréstimos | Robótica LMT')
@section('page-title', 'Empréstimos')
@section('content')
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4"><div><h1 class="h3 fw-bold mb-1">Empréstimos</h1><p class="text-muted mb-0">Acompanhe retiradas, prazos e devoluções.</p></div><a href="{{ route('emprestimos.create') }}" class="btn btn-sesi"><i class="fa-solid fa-plus me-2"></i>Novo Empréstimo</a></div>
<form method="GET" class="card card-clean p-3 mb-3"><div class="row g-3 align-items-end"><div class="col-md-8"><label class="form-label">Pesquisar usuário</label><input name="busca" class="form-control" value="{{ request('busca') }}"></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">Todos</option>@foreach(['ativo'=>'Ativo','devolvido'=>'Devolvido','atrasado'=>'Atrasado'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-1 d-grid"><button class="btn btn-dark">Filtrar</button></div></div></form>
<div class="card card-clean"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Usuário</th><th>Material</th><th>Quantidade</th><th>Data</th><th>Devolução</th><th>Status</th><th>Observação</th><th>Ações</th></tr></thead><tbody>
@forelse($emprestimos as $emprestimo)<tr><td>{{ $emprestimo->usuario->nome ?? '—' }}</td><td>{{ $emprestimo->material->nome ?? '—' }}</td><td>{{ $emprestimo->item->quantidade ?? '—' }}</td><td>{{ $emprestimo->data_emprestimo }}</td><td>{{ $emprestimo->data_devolucao ?: '—' }}</td><td><span class="badge {{ $emprestimo->status === 'devolvido' ? 'text-bg-success' : ($emprestimo->status === 'atrasado' ? 'text-bg-danger' : 'text-bg-warning') }}">{{ ucfirst($emprestimo->status) }}</span></td><td>{{ $emprestimo->observacao ?: '—' }}</td><td class="text-nowrap"><a class="btn btn-sm btn-outline-dark" href="{{ route('emprestimos.show', $emprestimo) }}"><i class="fa-regular fa-eye"></i></a> <a class="btn btn-sm btn-outline-primary" href="{{ route('emprestimos.edit', $emprestimo) }}"><i class="fa-solid fa-pen"></i></a> <form class="d-inline" method="POST" action="{{ route('emprestimos.destroy', $emprestimo) }}" onsubmit="return confirm('Excluir este empréstimo?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fa-solid fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="8" class="text-center p-5 text-muted">Nenhum empréstimo cadastrado.</td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $emprestimos->links('pagination::bootstrap-5') }}</div></div>
@endsection
