@extends('layout.principal')
@section('title', 'Início | Robótica LMT')
@section('page-title', 'Painel Geral')
@section('content')
<div class="mb-4"><h1 class="h3 fw-bold mb-1">Olá, {{ session('usuario_nome', 'Usuário') }}</h1><p class="text-muted mb-0">Acompanhe o inventário e as solicitações do laboratório.</p></div>
<div class="row g-3 mb-4">
@foreach([['Total de materiais',$totalMateriais,'fa-box','Inventário cadastrado'],['Empréstimos ativos',$emprestimosAtivos,'fa-hand-holding','Itens em circulação'],['Pedidos pendentes',$pedidosPendentes,'fa-clipboard-list','Aguardando análise'],['Materiais em manutenção',$materiaisManutencao,'fa-screwdriver-wrench','Itens indisponíveis']] as [$label,$value,$icon,$sub])<div class="col-sm-6 col-xl-3"><div class="card card-clean p-3 h-100"><div class="d-flex justify-content-between"><div><div class="small text-muted text-uppercase">{{ $label }}</div><div class="fs-3 fw-bold mt-2">{{ $value }}</div><div class="small text-muted">{{ $sub }}</div></div><i class="fa-solid {{ $icon }} text-secondary mt-1"></i></div></div></div>@endforeach
</div>
<div class="row g-3"><div class="col-xl-5"><div class="card card-clean p-4 h-100"><h2 class="h6 fw-bold">Movimentações dos últimos 7 dias</h2><p class="small text-muted">Empréstimos registrados por dia</p><div class="d-flex align-items-end justify-content-around border-bottom" style="height:220px">@php($maxMov = max(1, $movimentacoes->max('total')))@foreach($movimentacoes as $mov)<div class="d-flex flex-column align-items-center justify-content-end h-100 gap-2"><span class="small">{{ $mov['total'] ?: '' }}</span><div class="rounded-top {{ $loop->last ? 'bg-danger' : 'bg-dark' }}" style="width:22px;height:{{ max(4, (int)($mov['total'] / $maxMov * 145)) }}px"></div><span class="small text-muted">{{ $mov['dia'] }}</span></div>@endforeach</div></div></div>
<div class="col-xl-7"><div class="card card-clean p-4 h-100"><div class="d-flex justify-content-between align-items-center mb-2"><div><h2 class="h6 fw-bold mb-1">Empréstimos recentes</h2><p class="small text-muted mb-0">Últimas retiradas registradas</p></div><a href="{{ route('emprestimos.index') }}" class="small text-danger">Ver todos</a></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Material</th><th>Usuário</th><th>Data</th><th>Status</th></tr></thead><tbody>@forelse($recentes as $emprestimo)<tr><td>{{ $emprestimo->material->nome ?? '—' }}</td><td>{{ $emprestimo->usuario->nome ?? '—' }}</td><td>{{ $emprestimo->data_emprestimo }}</td><td><span class="badge {{ $emprestimo->status==='devolvido'?'text-bg-success':($emprestimo->status==='atrasado'?'text-bg-danger':'text-bg-warning') }}">{{ ucfirst($emprestimo->status) }}</span></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">Ainda não há empréstimos.</td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection
