<div class="row g-3">
    <div class="col-md-4"><label class="form-label">Código *</label><input name="codigo" class="form-control" value="{{ old('codigo', $material->codigo) }}" required>@error('codigo')<div class="text-danger small">{{ $message }}</div>@enderror</div>
    <div class="col-md-8"><label class="form-label">Nome *</label><input name="nome" class="form-control" value="{{ old('nome', $material->nome) }}" required>@error('nome')<div class="text-danger small">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Categoria</label><select name="id_categoria" class="form-select"><option value="">Selecione</option>@foreach($categorias as $categoria)<option value="{{ $categoria->id }}" @selected(old('id_categoria', $material->id_categoria) == $categoria->id)>{{ $categoria->nome ?? $categoria->descricao ?? ('Categoria '.$categoria->id) }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Localização</label><select name="id_localizacao" class="form-select"><option value="">Selecione</option>@foreach($localizacoes as $localizacao)<option value="{{ $localizacao->id }}" @selected(old('id_localizacao', $material->id_localizacao) == $localizacao->id)>{{ $localizacao->nome ?? $localizacao->descricao ?? ('Localização '.$localizacao->id) }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Tipo de material</label><input name="tipo_material" class="form-control" value="{{ old('tipo_material', $material->tipo_material) }}"></div>
    <div class="col-md-4"><label class="form-label">Quantidade total *</label><input type="number" min="0" name="quantidade" class="form-control" value="{{ old('quantidade', $material->quantidade ?? 0) }}" required></div>
    <div class="col-md-4"><label class="form-label">Disponível</label><input type="number" min="0" name="quantidade_disponivel" class="form-control" value="{{ old('quantidade_disponivel', $material->quantidade_disponivel) }}"><div class="form-text">Se ficar vazio ao cadastrar, será igual ao estoque total.</div></div>
    <div class="col-md-4"><label class="form-label">Quantidade mínima</label><input type="number" min="0" name="quantidade_minima" class="form-control" value="{{ old('quantidade_minima', $material->quantidade_minima ?? 0) }}"></div>
    <div class="col-md-4"><label class="form-label">Estado *</label><select name="estado" class="form-select" required>@foreach(['Disponível','Em manutenção','Indisponível'] as $estado)<option @selected(old('estado', $material->estado ?? 'Disponível') === $estado)>{{ $estado }}</option>@endforeach</select></div>
    <div class="col-12"><label class="form-label">Descrição</label><textarea name="descricao" rows="4" class="form-control">{{ old('descricao', $material->descricao) }}</textarea></div>
</div>
