@extends('layout.principal')
@section('title', 'Materiais | Robótica LMT')
@section('page-title', 'Materiais')
@section('content')
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4"><div><h1 class="h3 fw-bold mb-1">Inventário de Materiais</h1><p class="text-muted mb-0">Consulte e mantenha o cadastro de materiais do laboratório.</p></div><a href="{{ route('materiais.create') }}" class="btn btn-sesi"><i class="fa-solid fa-plus me-2"></i>Novo Material</a></div>
<form method="GET" class="card card-clean p-3 mb-3"><div class="row g-3 align-items-end"><div class="col-md-6"><label class="form-label">Pesquisar</label><input name="busca" value="{{ request('busca') }}" class="form-control" placeholder="Nome ou código"></div><div class="col-md-3"><label class="form-label">Categoria</label><select class="form-select" name="categoria"><option value="">Todas</option>@foreach($categorias as $categoria)<option value="{{ $categoria->id }}" @selected(request('categoria') == $categoria->id)>{{ $categoria->nome ?? $categoria->descricao ?? ('Categoria '.$categoria->id) }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Estado</label><select class="form-select" name="estado"><option value="">Todos</option>@foreach(['Disponível','Em manutenção','Indisponível'] as $estado)<option @selected(request('estado') === $estado)>{{ $estado }}</option>@endforeach</select></div><div class="col-md-1 d-grid"><button class="btn btn-dark">Filtrar</button></div></div></form>
<div class="card card-clean"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Código</th><th>Nome do item</th><th>Categoria</th><th>Localização</th><th>Estoque</th><th>Disponível</th><th>Estado</th><th>Ações</th></tr></thead><tbody>
@forelse($materiais as $material)<tr><td>{{ $material->codigo }}</td><td class="fw-semibold">{{ $material->nome }}</td><td>{{ $categorias->firstWhere('id', $material->id_categoria)->nome ?? '—' }}</td><td>{{ $localizacoes->firstWhere('id', $material->id_localizacao)->nome ?? '—' }}</td><td>{{ $material->quantidade }}</td><td>{{ $material->quantidade_disponivel }}</td><td><span class="badge text-bg-light border">{{ $material->estado }}</span></td><td class="text-nowrap"><a href="{{ route('materiais.show', $material) }}" class="btn btn-sm btn-outline-dark" title="Visualizar"><i class="fa-regular fa-eye"></i></a> <a href="{{ route('materiais.edit', $material) }}" class="btn btn-sm btn-outline-primary" title="Editar"><i class="fa-solid fa-pen"></i></a> <form class="d-inline" method="POST" action="{{ route('materiais.destroy', $material) }}" onsubmit="return confirm('Excluir este material?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" title="Excluir"><i class="fa-solid fa-trash"></i></button></form></td></tr>
@empty<tr><td colspan="8" class="text-center py-5 text-muted">Nenhum material encontrado. <a href="{{ route('materiais.create') }}">Cadastre o primeiro.</a></td></tr>@endforelse
</tbody></table></div><div class="p-3">{{ $materiais->links('pagination::bootstrap-5') }}</div></div>
@endsection
