@extends('layout.principal')
@section('title', 'Pedidos | Robótica LMT')
@section('page-title', 'Pedidos')
@section('content')
<div class="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4"><div><h1 class="h3 fw-bold mb-1">Pedidos de Materiais</h1><p class="text-muted mb-0">Registre solicitações e acompanhe a disponibilidade.</p></div><a href="{{ route('pedidos.create') }}" class="btn btn-sesi"><i class="fa-solid fa-plus me-2"></i>Novo Pedido</a></div>
<div class="card card-clean p-3 mb-4"><div class="d-flex align-items-center justify-content-between flex-wrap gap-2"><div class="text-center px-3"><span class="badge text-bg-dark">1</span><div class="small mt-1">Solicitar empréstimo</div></div><i class="fa-solid fa-arrow-right text-muted"></i><div class="text-center px-3"><span class="badge text-bg-dark">2</span><div class="small mt-1">Verificar disponibilidade</div></div><i class="fa-solid fa-arrow-right text-muted"></i><div class="text-center px-3"><span class="badge text-bg-success">SIM</span><div class="small mt-1">Autorizar retirada</div></div><i class="fa-solid fa-arrow-right text-muted"></i><div class="text-center px-3"><span class="badge text-bg-danger">NÃO</span><div class="small mt-1">Informar indisponibilidade</div></div></div></div>
<form method="GET" class="card card-clean p-3 mb-3"><div class="row g-3 align-items-end"><div class="col-md-9"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">Todos</option>@foreach(['pendente'=>'Pendente','aprovado'=>'Aprovado','negado'=>'Negado','concluido'=>'Concluído'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-3 d-grid"><button class="btn btn-dark">Filtrar pedidos</button></div></div></form>
<div class="card card-clean"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Usuário</th><th>Material</th><th>Quantidade</th><th>Data do pedido</th><th>Status</th><th>Observação</th><th>Ações</th></tr></thead><tbody>@forelse($pedidos as $pedido)<tr><td>{{ $pedido->usuario->nome ?? '—' }}</td><td>{{ $pedido->material->nome ?? '—' }}</td><td>{{ $pedido->item->quantidade ?? '—' }}</td><td>{{ $pedido->data_pedido }}</td><td><span class="badge {{ $pedido->status==='aprovado'?'text-bg-success':($pedido->status==='negado'?'text-bg-danger':($pedido->status==='concluido'?'text-bg-secondary':'text-bg-warning')) }}">{{ ucfirst($pedido->status) }}</span></td><td>{{ $pedido->observacao ?: '—' }}</td><td class="text-nowrap"><a class="btn btn-sm btn-outline-dark" href="{{ route('pedidos.show', $pedido) }}"><i class="fa-regular fa-eye"></i></a> <a class="btn btn-sm btn-outline-primary" href="{{ route('pedidos.edit', $pedido) }}"><i class="fa-solid fa-pen"></i></a> <form class="d-inline" method="POST" action="{{ route('pedidos.destroy', $pedido) }}" onsubmit="return confirm('Excluir este pedido?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fa-solid fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="7" class="text-center p-5 text-muted">Nenhum pedido cadastrado.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $pedidos->links('pagination::bootstrap-5') }}</div></div>
@endsection
